---

- name: Create sudo group
  group:
    name: sudo
    state: present

- name: Set a default value for "additional_users"
  set_fact:
    additional_users: "{{ additional_users | default([]) }}"
  tags: user-keys

- name: Combine "users" and "additional users"
  set_fact:
    users: "{{ users | combine(additional_users) }}"
  tags: user-keys

# To not install all Megaphone users, override users.
- name: Add Megaphone Users
  user:
    name: "{{ item.value.name }}"
    shell: "{{ item.value.shell | default('/usr/bin/bash')}}"
    groups: "{{ item.value.groups | default(omit) }}"
    password: "{{ item.value.password | default(omit) }}"
    state: "{{ item.value.state | default('present') }}"
    remove: "{{ item.value.remove | default('no') }}"
    update_password: "{{ item.value.update_password | default('on_create') }}"
    append: yes
  with_dict: "{{ users }}"

- name: Add authorized key
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - authorized
  tags: user-keys

- name: Add sudo group to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) ALL'

- name: Add dotfiles
  git:
    repo: "{{ item.value.dotfiles }}"
    dest: ~/dotfiles
    version: master
  when: item.value.dotfiles is defined
  become: yes
  become_user: "{{ item.value.name }}"
  with_dict: "{{ users }}"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"
  tags: dotfiles

- name: Execute dotfile script
  command: ~/dotfiles/makesymlinks.sh
  args:
    creates: ~/dotfiles_old
  when: item.value.dotfiles is defined
  become: yes
  become_user: "{{ item.value.name }}"
  with_dict: "{{ users }}"
